### ISSUE TITLE
[BUG] Error: There is a problemm with the given link!

### ISSUE THREAD

**Issue by officialdittaz** [phaticusthiccy/Open-APIs#35]
Error: There is a problemm with the given link!
    at Object.insta_reel (/home/runner/EXTREAM-BOTZ/node_modules/@phaticusthiccy/open-apis/InstaDownloader/start/instagram_reel.js:9:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

my code:

case 'ig':{
  if(!q) return setReply("Masukan Link")
setReply(mess.wait)
if (!args[0].match(/https:\/\/www.instagram.com\/(p|reel|tv)/gi)) return setReply( `*Link salah! Perintah ini untuk mengunduh postingan ig/reel/tv, bukan untuk highlight/story!*\n\ncontoh:\n${prefix + command} https://www.instagram.com/p/BmjK1KOD_UG/?utm_medium=copy_link`)

let igreel = q.includes("https://www.instagram.com/reel/")

if(igreel){

Download.insta_reel(q).then(async (data) => {
await xdev.sendMessage(from, {caption: `Nih`, video: {url: data.url} }, {quoted: dev})
console.log(data)
console.log(data.url)
})
} else {
let { instagramdl, instagramdlv2 } = require('@bochilteam/scraper')
let results = await instagramdl(args[0]).catch(async _ => await instagramdlv2(args[0]))
for (const { url } of results) await xdev.sendMedia(from, url, dev, {caption: "Nih"})
}
}
break

command: Ig https://www.instagram.com/reel/CfliL4Jhcyx/?igshid=YmMyMTA2M2Y=

**Comment by officialdittaz** [comment]
i use 1.8.3 version hehe

**Comment by phaticusthiccy** [comment]
Thanks for the feedback.
It was enough to post the error part :) Anyway, I'll take care of the error.

**Comment by officialdittaz** [comment]
> Thanks for the feedback. It was enough to post the error part :) Anyway, I'll take care of the error.

oh yeah :v

**Comment by phaticusthiccy** [comment]
Fixed in #36 

# 1) 
![image](https://user-images.githubusercontent.com/74794033/177180093-d5147133-cde7-4319-94fb-2df570862eb4.png)

# 
# 2) 
![image](https://user-images.githubusercontent.com/74794033/177180180-b42036fa-c583-4cee-a001-4238ba8428eb.png)

# 
# 3) 
![image](https://user-images.githubusercontent.com/74794033/177180367-c075ed83-8f9f-4524-9936-d06d56637594.png)

# 
# 4) 
![image](https://user-images.githubusercontent.com/74794033/177180435-5fe143bd-7d27-459e-af0f-ed4ff708ac4f.png)

# 

[Please check the new documention.](https://github.com/phaticusthiccy/Open-APIs/tree/main/InstaDownloader#reel-downloader)

Please use `npm test` at once on your device. 

Have a nice day.

**Comment by officialdittaz** [comment]
> Fixed in #36
> 
> # 1)
> ![image](https://user-images.githubusercontent.com/74794033/177180093-d5147133-cde7-4319-94fb-2df570862eb4.png)
> 
> # 2)
> ![image](https://user-images.githubusercontent.com/74794033/177180180-b42036fa-c583-4cee-a001-4238ba8428eb.png)
> 
> # 3)
> ![image](https://user-images.githubusercontent.com/74794033/177180367-c075ed83-8f9f-4524-9936-d06d56637594.png)
> 
> # 4)
> ![image](https://user-images.githubusercontent.com/74794033/177180435-5fe143bd-7d27-459e-af0f-ed4ff708ac4f.png)
> 
> [Please check the new documention.](https://github.com/phaticusthiccy/Open-APIs/tree/main/InstaDownloader#reel-downloader)
> 
> Please use `npm test` at once on your device.
> 
> Have a nice day.

Thanks its work 😁
